### ISSUE TITLE
代码clone下来，页面上有些功能没办法直接使用？

### ISSUE THREAD

**Issue by hpulzl** [instaer/aviator-rule-engine#10]
![image](https://github.com/instaer/aviator-rule-engine/assets/11573265/8c99b748-d0e2-490f-823a-97ddf5d40a25)
这个规则表达式没办法编辑
![image](https://github.com/instaer/aviator-rule-engine/assets/11573265/dddbd37a-da8a-409d-830d-27f3d3d8fca2)
规则集编码不能使用

**Comment by instaer** [comment]
规则集的表达式是在配置规则、条件后自动生成的，无法直接修改，此处文本框是只读的，这里加个提示比较好。
<规则管理>这里需要先输入已经创建好的规则集编码，然后再对下面的规则进行维护。后面我看看怎么调整交互方式

**Comment by hpulzl** [comment]
OK，这里各种条件是在哪里配置呢？
![image](https://github.com/instaer/aviator-rule-engine/assets/11573265/be0255f6-35a0-469b-b06b-72a41f7027c9)

**Comment by instaer** [comment]
> OK，这里各种条件是在哪里配置呢？ ![image](https://private-user-images.githubusercontent.com/11573265/302082567-be0255f6-35a0-469b-b06b-72a41f7027c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzMDU1NzMsIm5iZiI6MTcwODMwNTI3MywicGF0aCI6Ii8xMTU3MzI2NS8zMDIwODI1NjctYmUwMjU1ZjYtMzVhMC00NjliLWIwNmItNzJhNDFmNzAyN2M5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE5VDAxMTQzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliNGQ2YzU2ODliODU4YzZjZTNlN2I4OWJlZTBkOTU1N2ZjZjIwZmRlYjhhZWRlNTllMzZhMjZhOTQ4NjdjOWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vLDDkxu9qOK2qLWaNDwB52XFVvpOU3QT9fskIlNwpBU)

勾选对应的规则，点击配置按钮
