### ISSUE TITLE
关于如何进行配置的一些问题

### ISSUE THREAD

**Issue by LeToNode** [instaer/aviator-rule-engine#7]
如果结合前端来实现配置界面的，可能首先是要配置每个条件的左值的类型定义。比如示例中提及的关于费率计算的示例来说，
首先要配置参数变量的内容（包含展示名称，变量名称和变量类型，变量类型会影响后续的条件判断的可选择内容）这个主要是为了方便非技术人员可以字节选择条件。
示例的配置就需要配置{varLabel: "年龄"，varName:"age",varType:"Number"} {varLabel: "费用"，varName:"amt",varType:"Number"}
运营在配置条件时，就可以先选择条件左值的参数，然后根据这个varType，再进行可选的运算比较条件，以及填入右值。

ConditionRelationType 这些内容选择应该是与变量类型挂钩的，比如字符串应该返回StringCondition的ConditionRelationType可选择项和IntervalCondition的INTERVAL_STRING_LENGTH 数值型才有比较大小和判断数值范围这些的选择。

这里主要是考虑到配置的技术无关型，增加条件左值或者右值的配置选择。
当然这个再自己做一层业务封装来解决这个问题。

**Comment by instaer** [comment]
感谢你的建议。

在配置条件时选择的关系运算类型就已经决定了变量类型，我们可能不需要专门指定变量类型来限制可选的关系运算类型。

举个例子，若条件关系运算类型为INTERVAL_NUMBER（数值区间），变量类型必然是数值类型；若条件关系运算类型为REGEX（正则），变量类型必然是字符串类型。
