### ISSUE TITLE
我在想ui上做这个配置的时候，如何更直观的展示条件间的优先级的效果？

### ISSUE THREAD

**Issue by LeToNode** [instaer/aviator-rule-engine#8]
不知道你有什么好的想法没有

**Comment by instaer** [comment]
- 使用颜色来表示优先级
给每个条件分配一个特定的颜色，颜色的深浅可以表示不同的优先级。例如，红色代表最高优先级，绿色代表最低优先级;

- 使用进度条组件来表示优先级
在每个条件旁边加上一个进度条，用来显示该条件与其他条件的优先级关系。进度条的长度可以根据优先级值的大小来调整；
